"""added gpu_id to gpu_loads

Revision ID: 2025_12_25_0001
Revises: 2025_12_25_0000
Create Date: 2025-12-25 00:01:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2025_12_25_0001'
down_revision = '2025_12_25_0000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first
    op.add_column('gpu_loads', sa.Column('gpu_id', sa.String(), nullable=True))
    
    # 2. Update existing records with a default value
    op.execute("""
    UPDATE gpu_loads 
    SET gpu_id = 'unknown:unknown:0' 
    WHERE gpu_id IS NULL
    """)
    
    # 3. Make the column non-nullable
    op.alter_column('gpu_loads', 'gpu_id', nullable=False)
    
    # 4. Create the index
    op.create_index(op.f('ix_gpu_loads_gpu_id'), 'gpu_loads', ['gpu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_loads_gpu_id'), table_name='gpu_loads')
    op.drop_column('gpu_loads', 'gpu_id')
    # ### end Alembic commands ###
