"""added worker and gpu log tables

Revision ID: 2025_12_25_0002
Revises: 2025_12_25_0001
Create Date: 2025-12-25 00:02:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2025_12_25_0002'
down_revision = '2025_12_25_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=True),
    sa.Column('log_content', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_worker_id'), 'worker_logs', ['worker_id'], unique=False)
    
    op.create_table('gpu_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=True),
    sa.Column('log_content', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_logs_gpu_id'), 'gpu_logs', ['gpu_id'], unique=False)
    op.create_index(op.f('ix_gpu_logs_worker_id'), 'gpu_logs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_logs_worker_id'), table_name='gpu_logs')
    op.drop_index(op.f('ix_gpu_logs_gpu_id'), table_name='gpu_logs')
    op.drop_table('gpu_logs')
    
    op.drop_index(op.f('ix_worker_logs_worker_id'), table_name='worker_logs')
    op.drop_table('worker_logs')
    # ### end Alembic commands ###
