"""added worker and gpu load tables

Revision ID: 2025_12_25_0000
Revises: 2aed534bd7b2
Create Date: 2025-12-25 00:00:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2025_12_25_0000'
down_revision = '2aed534bd7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=True),
    sa.Column('ram', sa.Float(), nullable=True),
    sa.Column('gpu', sa.Float(), nullable=True),
    sa.Column('vram', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_loads_worker_id'), 'worker_loads', ['worker_id'], unique=False)
    
    op.create_table('gpu_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=False),
    sa.Column('gpu_utilization', sa.Float(), nullable=True),
    sa.Column('vram_utilization', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_loads_worker_id'), 'gpu_loads', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_loads_worker_id'), table_name='gpu_loads')
    op.drop_table('gpu_loads')
    
    op.drop_index(op.f('ix_worker_loads_worker_id'), table_name='worker_loads')
    op.drop_table('worker_loads')
    # ### end Alembic commands ###
