"""Add report tables

Revision ID: 2026_01_21_1500
Revises: 2026_01_20_1500
Create Date: 2026-01-21 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2026_01_21_1500'
down_revision: Union[str, None] = '2026_01_20_1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types first using DO block to check if they exist
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reporttypeenum') THEN CREATE TYPE reporttypeenum AS ENUM ('gpu', 'worker'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reportstatusenum') THEN CREATE TYPE reportstatusenum AS ENUM ('pending', 'generating', 'completed', 'failed'); END IF; END $$;")
    
    # Create reports table using PostgreSQL native enum types
    op.execute('''
    CREATE TABLE IF NOT EXISTS reports (
        deleted_at TIMESTAMP,
        name VARCHAR NOT NULL,
        type reporttypeenum NOT NULL,
        start_time TIMESTAMP NOT NULL,
        end_time TIMESTAMP NOT NULL,
        user_group_id INTEGER,
        status reportstatusenum NOT NULL,
        file_path VARCHAR,
        description VARCHAR,
        id SERIAL PRIMARY KEY,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    ''')
    
    # Create report_details table using PostgreSQL native enum types
    op.execute('''
    CREATE TABLE IF NOT EXISTS report_details (
        deleted_at TIMESTAMP,
        metric_name VARCHAR NOT NULL,
        metric_value FLOAT NOT NULL,
        metric_unit VARCHAR NOT NULL,
        timestamp TIMESTAMP NOT NULL,
        resource_id VARCHAR NOT NULL,
        resource_name VARCHAR,
        user_group_id INTEGER,
        user_group_name VARCHAR,
        id SERIAL PRIMARY KEY,
        report_id INTEGER REFERENCES reports(id),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    ''')
    
    # Add indexes
    op.create_index('idx_reports_created_at', 'reports', ['created_at'])
    op.create_index('idx_reports_status', 'reports', ['status'])
    op.create_index('idx_reports_type', 'reports', ['type'])
    op.create_index('idx_reports_user_group_id', 'reports', ['user_group_id'])
    
    op.create_index('idx_report_details_metric_name', 'report_details', ['metric_name'])
    op.create_index('idx_report_details_resource_id', 'report_details', ['resource_id'])
    op.create_index('idx_report_details_timestamp', 'report_details', ['timestamp'])
    op.create_index('idx_report_details_user_group_id', 'report_details', ['user_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_report_details_user_group_id', table_name='report_details')
    op.drop_index('idx_report_details_timestamp', table_name='report_details')
    op.drop_index('idx_report_details_resource_id', table_name='report_details')
    op.drop_index('idx_report_details_metric_name', table_name='report_details')
    
    op.drop_index('idx_reports_user_group_id', table_name='reports')
    op.drop_index('idx_reports_type', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_created_at', table_name='reports')
    
    # Drop tables
    op.drop_table('report_details')
    op.drop_table('reports')
    
    # Drop enum types
    op.execute("DROP TYPE reportstatusenum")
    op.execute("DROP TYPE reporttypeenum")
    # ### end Alembic commands ###
