"""Add model catalog tables

Revision ID: 2026_01_26_1500
Revises: 2026_01_21_1500
Create Date: 2026-01-26 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2026_01_26_1500'
down_revision: Union[str, None] = '2026_01_21_1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create model_catalog table
    op.execute('''
    CREATE TABLE IF NOT EXISTS model_catalog (
        deleted_at TIMESTAMP,
        name VARCHAR NOT NULL,
        description VARCHAR,
        home VARCHAR,
        icon VARCHAR,
        size FLOAT,
        activated_size FLOAT,
        size_unit VARCHAR,
        categories JSONB,
        capabilities JSONB,
        licenses JSONB,
        release_date DATE,
        is_deployed BOOLEAN DEFAULT FALSE,
        id SERIAL PRIMARY KEY,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    ''')

    # Create model_catalog_spec table
    op.execute('''
    CREATE TABLE IF NOT EXISTS model_catalog_spec (
        deleted_at TIMESTAMP,
        model_catalog_id INTEGER NOT NULL,
        mode VARCHAR,
        quantization VARCHAR,
        gpu_filters JSONB,
        source VARCHAR,
        huggingface_repo_id VARCHAR,
        huggingface_filename VARCHAR,
        model_scope_model_id VARCHAR,
        model_scope_file_path VARCHAR,
        local_path VARCHAR,
        backend VARCHAR,
        backend_version VARCHAR,
        backend_parameters JSONB,
        env JSONB,
        id SERIAL PRIMARY KEY,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (model_catalog_id) REFERENCES model_catalog(id) ON DELETE CASCADE
    )
    ''')

    # Add indexes
    op.create_index(
        'idx_model_catalog_name',
        'model_catalog',
        ['name']
    )
    op.create_index(
        'idx_model_catalog_categories',
        'model_catalog',
        ['categories'],
        postgresql_using='gin'
    )
    op.create_index(
        'idx_model_catalog_is_deployed',
        'model_catalog',
        ['is_deployed']
    )
    op.create_index(
        'idx_model_catalog_spec_model_catalog_id',
        'model_catalog_spec',
        ['model_catalog_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index(
        'idx_model_catalog_spec_model_catalog_id',
        table_name='model_catalog_spec'
    )
    op.drop_index(
        'idx_model_catalog_is_deployed',
        table_name='model_catalog'
    )
    op.drop_index(
        'idx_model_catalog_categories',
        table_name='model_catalog',
        postgresql_using='gin'
    )
    op.drop_index(
        'idx_model_catalog_name',
        table_name='model_catalog'
    )

    # Drop tables
    op.drop_table('model_catalog_spec')
    op.drop_table('model_catalog')
    # ### end Alembic commands ###
